name: SonarQube Analysis

on:
  push:
    branches:
      - main # Cambia esto si quieres analizar otra rama.
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Asegúrate de configurar este secreto en tu repositorio
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=Seguridad_Project2024 \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
